apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-deploy-test-lab-f751b2/contact-manager:latest
    docker:
      cacheFrom:
      - gcr.io/cloud-deploy-test-lab-f751b2/contact-manager:latest
  googleCloudBuild:
    projectId: ${PROJECT_ID}
deploy:
 kustomize:
   paths: 
   - ../kustomize
# portForward:
#   - resourceType: deployment
#     resourceName: contact-manager-svc
#     port: 8080
#     localPort: 9000