kind: Service
apiVersion: v1
metadata:
  name: contact-manager-svc
spec:
  selector:
    deployment: contact-manager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080