apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: contact-manager
description: Anna's test pipeline
serialPipeline:
 stages:
 - targetId: test
   profiles: []
 - targetId: staging   
   profiles: [] 
 - targetId: prod
   profiles: []   
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: contact-manager-test
description: development cluster
gke:
 cluster: projects/PROJECT_ID/locations/us-central1/clusters/test
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: contact-manager-staging
description: development cluster
gke:
 cluster: projects/PROJECT_ID/locations/us-central1/clusters/staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: contact-manager-prod
description: development cluster
gke:
 cluster: projects/PROJECT_ID/locations/us-central1/clusters/prod
---
