apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: contact-manager
description: Anna's test pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging   
 - targetId: prod
