apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: contact-manager
description: Anna's test pipeline
serialPipeline:
 stages:
 - targetId: test
   profiles: []
 - targetId: staging   
   profiles: [] 
 - targetId: prod
   profiles: []   
